-- Does not include meta columns because this should not be user editable?
CREATE TABLE IF NOT EXISTS transaction_relationship (
    relationship_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT
);
