#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER han WITH PASSWORD 'p@ssw0rd!';
CREATE USER chewie WITH PASSWORD 'p@ssw0rd!';
GRANT ALL PRIVILEGES ON DATABASE imsdb TO han;
GRANT ALL PRIVILEGES ON DATABASE imsdb TO chewie;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO han;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO chewie;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO han;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chewie;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO han;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO chewie;

EOSQL

echo "Users created and default permissions granted"